name: mono-deal
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.5.0
  - anyio=3.7.1
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - click=8.1.6
  - exceptiongroup=1.1.2
  - fastapi=0.101.0
  - h11=0.14.0
  - idna=3.4
  - libffi=3.4.4
  - openssl=3.1.2
  - pip=23.2.1
  - pydantic=2.0.3
  - pydantic-core=2.3.0
  - python=3.10.12
  - python_abi=3.10
  - setuptools=68.0.0
  - sniffio=1.3.0
  - sqlite=3.41.2
  - starlette=0.27.0
  - tk=8.6.12
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - uvicorn=0.23.2
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
